---
name: Check no cover Removal

on:
  workflow_dispatch:
  schedule:
    - cron:  "15 9 1 * *"

jobs:
  check-no-cover:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@v1

      - name: Did coverage change?
        env:
          CI: 1
        run: |
          set -euo pipefail

          # stop ignoring no cover lines
          sed -i.bak 's/"pragma: no cover",/# "pragma: no cover",/' pyproject.toml

          just test-all | tee test-output.txt || true

          # extract missing lines per file fom coverage report in the tests output
          # python script: get the files table from coverage
          # awk: break the table down into filename and missing lines number
          python scripts/parse_coverage_output.py test-output.txt | awk '{ print $1 " " $3 }' - > no-cover.txt

          # compare coverage report to the existing one
          git diff --exit-code no-cover.txt
